bundler_args: --without development

matrix:
  allow_failures:
    rvm: 1.8.6

notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    urls:
      - http://dx-helper.herokuapp.com/travis

rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.2
  - 1.9.3

script: bundle exec rspec -bfs spec
